version: "3.7"
services:
 mobileshop:
    build: .
    container_name: mobileshop
    image: mobileshop:latest
    environment:
      - MYSQL_HOST=mysql
    ports:
      - 80:8080
    networks:
      - rest-network
    volumes:
      - java-data:/app/uploads
    depends_on:
      - mysql
 mysql:
    container_name: mysql
    command: --character-set-server=utf8mb4 --collationserver=utf8mb4_general_ci
    image: mysql:latest
    networks:
      - rest-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=mobileshop
      - MYSQL_USER=root
      - MYSQL_PASSWORD=lozinka
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
networks:
  rest-network:
    driver: bridge
volumes:
  mysql-data:
  java-data:
